# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8335e9938ba51046efec88dffb3687abb6d886a288fcdca5d84f5038991edc39fa0b9eb7fd538a36266abb40e4fec33ba497467c93912b1537f56814ae87848b

test:
  secret_key_base: 2d0e8dddf563ba3e71a4c90757376b76323b1d7a115b2484100030c02251f44eb91388afa9a7ef88d03f8b18d6c9dc15aa21cd7801cc28a895a691d8a2f2ceba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
